# Generated by Django 4.2.23 on 2026-06-27 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorlog',
            options={'managed': True},
        ),
    ]
