# Generated by Django 4.2.29 on 2026-05-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='source_platform',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('api', 'API')], default='web', max_length=50),
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
    ]
