# Generated by Django 4.2.29 on 2026-05-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
