# Generated by Django 4.2.29 on 2026-05-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_feedback_feedback_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
