# Generated by Django 6.0.5 on 2026-05-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_feedback_ai_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminactivity',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='newsedition',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='visitorlog',
            options={'managed': False},
        ),
    ]
