# Generated by Django 4.2.7 on 2026-05-23 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_adminactivity_options_alter_attribute_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminactivity',
            table='admin_activity',
        ),
        migrations.AlterModelTable(
            name='attribute',
            table='attributes',
        ),
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
        migrations.AlterModelTable(
            name='newsedition',
            table='news_editions',
        ),
        migrations.AlterModelTable(
            name='visitorlog',
            table='visitor_logs',
        ),
    ]
