# Generated by Django 4.2.29 on 2026-06-25 04:56

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_eventregistration_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='event_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='territory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('event_id'), name='uniq_lower_email_per_event'),
        ),
    ]
